sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

notifications:
  email: false

node_js:
  - 8

before_install:
  - npm i -g npm@^5.6.0
install: npm install
before_script:
  - npm prune
script:
  - npm run build
